name: Android CI
  
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build debug apk with Gradle
      run: cd project && bash ./gradlew clean assemble
    - uses: actions/upload-artifact@v2
      with:
        name: app-debug.apk
        path: project/app/build/outputs/apk/debug/app-debug.apk